### ISSUE TITLE
pass variable across tasks & parallel task

### ISSUE THREAD

**Issue by umeshpatra** [AMalininHere/camunda-worker-dotnet#10]
Hi Alexey,
I am trying to evaluate this version for one of our dotnet core application. Able to setup and run for simple external tasks. But finding difficult how to implement bellow features:
- Passing variable across task.
- Parallel task setup (forking and join)
- listening to RabbitMQ Event
- Rest API integration

Any samplecode including model or suggestion would be really great.
Regards,
Umesh

**Comment by AMalininHere** [comment]
@umeshpatra can you provide more details about your use cases?

**Comment by muhammad-sharifi** [comment]
@umeshpatra You can use Connector Service Task for REST requests instead of External Service Task.
A full [example ](https://github.com/camunda/camunda-bpm-examples/tree/master/servicetask/rest-service) of the REST connector can also be found in the [Camunda examples repository](https://github.com/camunda/camunda-bpm-examples) on GitHub
